flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- aeson-1.0.0.0
- data-default-class-0.0.1
- proto-lens-0.1.0.2
- proto-lens-protoc-0.1.0.2
explicit-setup-deps:
  ! '*': true
resolver: lts-7.0
