flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: https://github.com/dp-cylme/logging-effect-google.git
    commit: 2d0815d4d35e2442d0fab5d01373052f74ece3c3
- location:
    git: https://github.com/dp-cylme/wai-logging-effect-google.git
    commit: 83ea8d27aba804de166ef16bbd548ce82c6cfa8b
extra-deps:
- aeson-1.0.1.0
- data-default-0.6.0
- data-default-class-0.0.1
- data-default-instances-base-0.1.0
- fast-logger-2.4.7
- logging-effect-1.1.0
- proto-lens-0.1.0.2
- proto-lens-arbitrary-0.1.0.1
- proto-lens-protoc-0.1.0.2
- wai-extra-3.0.18
explicit-setup-deps:
  ! '*': true
resolver: lts-7.0

image:
  container:
    name: pinacta/negotians
    base: fpco/stack-run
